apiVersion: v1
kind: Service
metadata:
  name: gitops-foundations
  namespace: arc-exercise
spec:
  selector:
    app: gitops-foundations
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer